Add support fedora redhat
ait-aecid/aminer-ansible pull request #22
Opened 2023-11-23 10:23 UTC by ernstleierzopf

# Make sure these boxes are signed before submitting your Pull Request -- thank you.

# Must haves
- [ ] I have read and followed the contributing guide lines at https://github.com/ait-aecid/logdata-anomaly-miner/wiki/Git-development-workflow
- [ ] Issues exist (in ttps://github.com/ait-aecid/logdata-anomaly-miner) for this PR
- [ ] I added related issues using the "Fixes #<issue-id>"-notations
- [ ] This Pull-Requests merges into the "development"-branch

Fixes #1080

# Submission specific

- [ ] This PR adds required modules to the aminer installation
- [ ] This PR changes installations of existing modules
- [ ] This PR changes the default python version for the aminer

# Describe changes:
-

2023-11-23 14:06 UTC, whotwagner commented on tasks/main.yml
> -    state: link
Are those lines deleted on purpose?

2023-11-23 14:10 UTC, ernstleierzopf commented on tasks/main.yml
> -    state: link
yes, because in newer distributions there are apt/dnf packages (python3-scipy python3-numpy) and with these we do not need to link them. We only need to link packages installed via pip.

Please note this is still draft - I am using it to debug the playbook.

2023-11-23 14:11 UTC, whotwagner commented on tasks/main.yml
> -    state: link
ah, I just saw it now that this is a draft

2023-11-23 14:11 UTC, ernstleierzopf commented on tasks/main.yml
> -    state: link
because I just changed it a moment ago ;)

2023-11-23 14:36 UTC, ernstleierzopf commented on tasks/main.yml
> -- name: Link joblib
@whotwagner do you know where joblib is used? could not find it with grep.
I will test all of these changes locally by basically running the same commands as in the jenkinsfile.

2023-11-27 09:15 UTC, ernstleierzopf commented on tasks/main.yml
> -- name: Link joblib
I could test it, but is it worth to rebuild all of the docker images locally? This would take about 1 hour of build time + some time from me doing other tasks..
I suggest that we simply remove it and something in the testing pipeline should fail if this is not ok. Do you agree on that?

2023-11-27 09:25 UTC, ernstleierzopf commented on tasks/main.yml
> +    paths: "/usr"
I did not consider that too much, but some distributions have multiple paths in which packages are installed (i.e. /usr/lib64). Reconsidering it, we could change the aminer_pythonpath variable to be a list of paths instead of a single string.

I will try that - at least the rebuild will be worth it now. There actually was an issue with yaml, because it linked the ansible/yaml package instead which lead to an error.

2023-11-27 12:53 UTC, whotwagner commented on vars/debian-buster.yml
> +        - python3-pandas
please remove it and make some manual testing on your local machine

2023-11-27 15:29 UTC, ernstleierzopf commented on vars/debian-buster.yml
> +        - python3-pandas
seems like pandas is not needed. I will simply remove it within the new branch I created, as it only is a one-liner and let's see what happens.

2023-11-27 20:46 UTC, ernstleierzopf commented on vars/debian-buster.yml
> +        - python3-pandas
seems like pandas is not needed anywhere - I have removed it in ansible and in the main project.

2023-11-27 20:48 UTC, ernstleierzopf commented
I have built all of the supported docker files / configurations on my machine to make sure everything is compatible. Now everything is working and no hardcoded paths are used in the main config. They are still used in the buster.yml, but as this is only for one specifc OS version, which will be deprecated soon, it does not bother me that much.

2023-11-28 14:57 UTC, whotwagner requested changes

2023-11-28 14:57 UTC, whotwagner commented on tasks/RedHat.yml
> +    dest: /usr/lib/python3.9/site-packages/
Please don't use static python-versions. This will make us headaches in future releases

2023-11-28 14:57 UTC, whotwagner commented on tasks/RedHat.yml
> +  command: ls /usr/lib/python3.9/site-packages
make the path variable

2023-11-28 14:57 UTC, whotwagner commented on tasks/RedHat.yml
> +    dest: "/etc/aminer/conf-enabled/yaml"
Variable path to python

2023-11-28 14:57 UTC, whotwagner commented on tasks/debian-buster.yml
> +    paths: "/usr"
make the path more specific. otherwise we might get problems with duplicate matches

2023-11-28 14:57 UTC, whotwagner commented on tasks/debian-buster.yml
> +    paths: "/usr"
make the path more specific. otherwise we might get problems with duplicate matches

2023-11-28 14:57 UTC, whotwagner commented on tasks/debian-buster.yml
> +    paths: "/usr"
make the path more specific. otherwise we might get problems with duplicate matches

2023-11-28 14:57 UTC, whotwagner commented on tasks/fedora.yml
> +    src: "/usr/lib64/python3.12/site-packages/yaml"
please do not use hardcoded version strings. use variables for that

2023-11-28 15:19 UTC, ernstleierzopf commented on tasks/RedHat.yml
> +    dest: /usr/lib/python3.9/site-packages/
done.

2023-11-28 15:19 UTC, ernstleierzopf commented on tasks/RedHat.yml
> +  command: ls /usr/lib/python3.9/site-packages
done.

2023-11-28 16:27 UTC, ernstleierzopf commented
@whotwagner I have implemented and verified all requested changes by rebuilding the docker images and running them. The PR can be accepted now.

2023-11-28 19:20 UTC, whotwagner requested changes

2023-11-28 19:20 UTC, whotwagner commented on vars/debian-buster.yml
> +aminer_pythonpath: ['/usr/lib/python3/dist-packages', '/usr/lib/python3.7/dist-packages', '/usr/local/lib/python3.7/dist-packages']
Why do you use lists for this? Is it really necessary for one single release to have 3 different locations? This makes it harder to debug in the future.

2023-11-28 21:46 UTC, ernstleierzopf commented on vars/debian-buster.yml
> +aminer_pythonpath: ['/usr/lib/python3/dist-packages', '/usr/lib/python3.7/dist-packages', '/usr/local/lib/python3.7/dist-packages']
Unfortunately this is necessary, because packages are installed in different directories based on the source (apt, dnf - or pip). Even within dnf itself the installation location is not always the same, as some packages are installed in the /lib and some in /lib64 directory.
Don't ask me for the reason of this - I don't really understand the benefit doing it this way. 

Before my changes every single Debian/Ubuntu docker build failed, because the yaml module was not found using only the main pythonpath. These changes actually make the docker build really work. The test in jenkins does not work properly as it does not fail, if the docker image is built, because the linked packages are used from the host instead of the docker container. We probably should remove this parameter from the test: `-v $PWD/aminercfg:/etc/aminer`. Please notify me if I should try removing this parameter in the next aminer PR.

Debugging issues is actually really easy. If you see that the aminer is not working properly, look at the image build logs and search for skipped linking tasks. If there are some, rerun the build with ansible-playbook -v to see which packages were found. When multiple packages are found, simply select the specific location in the release specific tasks and link the package directly instead of searching for it first.

All of the locations can be printed with `python3 -c 'import site; print(site.getsitepackages())'`. They must be reorderd so the main path is first, and optionally the lib64 path is second in order.

2023-11-28 21:51 UTC, merged