Remove dependency on python3-pkg-resources
ait-aecid/aminer-ansible pull request #33
Opened 2024-10-28 20:46 UTC by ernstleierzopf

# Make sure these boxes are signed before submitting your Pull Request -- thank you.

# Must haves
- [ ] I have read and followed the contributing guide lines at https://github.com/ait-aecid/logdata-anomaly-miner/wiki/Git-development-workflow
- [ ] Issues exist (in ttps://github.com/ait-aecid/logdata-anomaly-miner) for this PR
- [ ] I added related issues using the "Fixes #<issue-id>"-notations
- [ ] This Pull-Requests merges into the "development"-branch

Fixes #1341

# Submission specific

- [ ] This PR adds required modules to the aminer installation
- [ ] This PR changes installations of existing modules
- [ ] This PR changes the default python version for the aminer

# Describe changes:
-

2024-10-29 10:22 UTC, whotwagner requested changes

2024-10-29 10:22 UTC, whotwagner commented on tasks/debian-buster.yml
> -
please keep it for the old debian buster

2024-10-30 09:28 UTC, ernstleierzopf commented on tasks/debian-buster.yml
> -
moved this to the main task so it is installed for all OSes via pip anyways. This would be a duplicate installation.

@whotwagner please review this again as no change is needed IMO.

2024-10-30 14:15 UTC, whotwagner approved these changes

2024-10-30 14:15 UTC, merged